### ISSUE TITLE
Feature Request: Approved Contact List for WhatsApp Integration

### ISSUE THREAD

**Issue by deanbirnie** [catalinberta/panko-gpt#12]
Only approved contacts (either name or number) defined in a list will be able to trigger the bot. Configured in the specific bots configuration page.

Would allow for custom bots for specific groups of people.

Thanks for your awesome app!

**Comment by catalinberta** [comment]
@deanbirnie 

Thanks for the suggestion, good feature to add as it allows multiple bots per number.

It's now implemented in v0.7.0 - #13
