### ISSUE TITLE
Selfhosting

### ISSUE THREAD

**Issue by japlic** [catalinberta/panko-gpt#5]
Add a option to self host the ai like open source ai

**Comment by catalinberta** [comment]
@japlic Could you elaborate? 

I think I get it, though I want to make sure. 
Are you asking that besides exposing bots to various messaging platforms, to also be able to launch web interfaces like chat.openai.com? If so, I'd like to better understand the advantages over their official implementation chat.openai.com

**Comment by japlic** [comment]
I mean like using a selfhosted ai model

**Comment by catalinberta** [comment]
Sorry for the late reply. I misunderstood your request and now that it is clear to me, adding the option to use own models makes sense. This will be in the next release, thanks!

**Comment by japlic** [comment]
Thank you
